from datetime import datetime, timezone

from langchain_openai import ChatOpenAI

from app.models.contracts import AgentResult
from app.models.implementation import (
    FileChange,
    ImplementationPlan,
    ImplementationResult,
)
from app.tools.gateway import ToolGateway


class ImplementationAgent:
    def __init__(
        self,
        mode: str,
        model: str,
        api_key: str | None,
        gateway: ToolGateway | None = None,
    ) -> None:
        self.mode = mode
        self.model = model
        self.api_key = api_key
        self.gateway = gateway or ToolGateway()

    def plan(
        self,
        requirements: dict,
        architecture: dict,
        security_review: dict,
    ) -> ImplementationPlan:
        if self.mode == "openai":
            llm = ChatOpenAI(
                model=self.model,
                temperature=0,
                api_key=self.api_key,
            ).with_structured_output(ImplementationPlan)

            result = llm.invoke(
                f"""
You are the STEH Implementation Agent.

Create an implementation plan that strictly follows the approved requirements,
architecture and security requirements.

Rules:
- Never include secrets.
- Never request shell access.
- Never escape the authorized workspace.
- Never delete files.
- Do not silently change architecture.
- Generate only files necessary for the requested implementation.
- Paths must be relative and contain only letters, numbers, underscore,
  hyphen, slash and dot.

REQUIREMENTS:
{requirements}

ARCHITECTURE:
{architecture}

SECURITY REVIEW:
{security_review}
"""
            )
            return ImplementationPlan.model_validate(result)

        return ImplementationPlan(
            summary="Create a minimal FastAPI customer API scaffold.",
            files=[
                FileChange(
                    path="generated_app/main.py",
                    reason="Minimal API entry point.",
                    content='''from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/health")\ndef health():\n    return {"status": "ok"}\n''',
                ),
                FileChange(
                    path="generated_app/README.md",
                    reason="Document generated scaffold and limitations.",
                    content=(
                        "# Generated Application\n\n"
                        "Generated by STEH Alpha 0.4 inside an isolated workspace.\n"
                    ),
                ),
            ],
            known_limitations=[
                "Alpha 0.4 generates files but does not execute them.",
                "Testing and scanners arrive in Alpha 0.5.",
            ],
        )

    def run(
        self,
        task_id: str,
        requirements: dict,
        architecture: dict,
        security_review: dict,
    ) -> AgentResult:
        plan = self.plan(requirements, architecture, security_review)

        max_files = int(self.gateway.policy["limits"]["max_files_per_task"])
        if len(plan.files) > max_files:
            raise ValueError("Implementation plan exceeds file limit.")

        results = []
        created = []
        modified = []

        for change in plan.files:
            result = self.gateway.write_file(
                task_id,
                change.path,
                change.content,
            )
            results.append(result)
            if result.message == "created":
                created.append(change.path)
            else:
                modified.append(change.path)

        implementation = ImplementationResult(
            plan=plan,
            files_created=created,
            files_modified=modified,
            tool_results=results,
        )

        return AgentResult(
            agent="implementation_agent",
            status="SUCCESS",
            result=implementation.model_dump(mode="json"),
            findings=[],
            evidence=[{
                "type": "implementation_workspace",
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "artifacts": created + modified,
            }],
            confidence=0.75 if self.mode == "stub" else 0.88,
        )
